import {
  one as agricOne,
  three as agricThree,
  two as agricTwo,
  six as agricSix,
  five as agricFive,
  four as agricFour,
} from "../../../assets/images/services/agriculture/card";

import {
  main as agricMain,
  sub as agricSub,
  subTwo as agricSubTwo,
  subThree as agricSubThree,
  subFour as agricSubFour,
} from "../../../assets/images/services/agriculture/product";

export const agricultural = {
  title: "Agricultural Investment",
  id: "agricultural-investment",
  desc: "We believe in the potential of agriculture to drive sustainable development. Ellington funds provides investment options in agriculture, supporting farmers and agribusinesses while delivering attractive returns to our investors.",
  products: [
    {
      id: "crowdfunding1",
      img: agricOne,
      extraImages: [
        agricMain,
        agricSub,
        agricSubTwo,
        agricSubThree,
        agricSubFour,
      ],
      title: "Grain farm",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "We believe in the potential of agriculture to drive sustainable development. Ellington funds provides investment options in agriculture, supporting farmers and agribusinesses while delivering attractive returns to our investors.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding2",
      img: agricTwo,
      extraImages: [
        agricMain,
        agricSub,
        agricSubTwo,
        agricSubThree,
        agricSubFour,
      ],
      title: "Grain Farm",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "We believe in the potential of agriculture to drive sustainable development. Ellington funds provides investment options in agriculture, supporting farmers and agribusinesses while delivering attractive returns to our investors.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding3",
      img: agricThree,
      extraImages: [
        agricMain,
        agricSub,
        agricSubTwo,
        agricSubThree,
        agricSubFour,
      ],
      title: "Grain Farm",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "We believe in the potential of agriculture to drive sustainable development. Ellington funds provides investment options in agriculture, supporting farmers and agribusinesses while delivering attractive returns to our investors.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding4",
      img: agricFour,
      extraImages: [
        agricMain,
        agricSub,
        agricSubTwo,
        agricSubThree,
        agricSubFour,
      ],
      title: "Grain Farm",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "We believe in the potential of agriculture to drive sustainable development. Ellington funds provides investment options in agriculture, supporting farmers and agribusinesses while delivering attractive returns to our investors.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding5",
      img: agricFive,
      extraImages: [
        agricMain,
        agricSub,
        agricSubTwo,
        agricSubThree,
        agricSubFour,
      ],
      title: "Grain Farm",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "We believe in the potential of agriculture to drive sustainable development. Ellington funds provides investment options in agriculture, supporting farmers and agribusinesses while delivering attractive returns to our investors.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding6",
      img: agricSix,
      extraImages: [
        agricMain,
        agricSub,
        agricSubTwo,
        agricSubThree,
        agricSubFour,
      ],
      title: "Grain Farm",
      info: { location: "lekki phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "We believe in the potential of agriculture to drive sustainable development. Ellington funds provides investment options in agriculture, supporting farmers and agribusinesses while delivering attractive returns to our investors.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
  ],
};
