import {
  one as donationsOne,
  three as donationsThree,
  two as donationsTwo,
  six as donationsSix,
  five as donationsFive,
  four as donationsFour,
} from "../../../assets/images/services/donation/card";

// content images

import {
  main as donationsMain,
  sub as donationsSub,
  subTwo as donationsSubTwo,
  subThree as donationsSubThree,
  subFour as donationsSubFour,
} from "../../../assets/images/services/donation/product";

export const donations = {
  title: "Donations",
  id: "donations",
  desc: "Our donations investment opportunities cater to the growing demand for efficient and sustainable donations solutions. Partner with Ellington funds to invest in the future of donations.",
  products: [
    {
      id: "crowdfunding1",
      img: donationsOne,
      extraImages: [
        donationsMain,
        donationsSub,
        donationsSubTwo,
        donationsSubThree,
        donationsSubFour,
      ],
      title: "NGO Donations",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Our donations investment opportunities cater to the growing demand for efficient and sustainable donations solutions. Partner with Ellington funds to invest in the future of donations.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding2",
      img: donationsTwo,
      extraImages: [
        donationsMain,
        donationsSub,
        donationsSubTwo,
        donationsSubThree,
        donationsSubFour,
      ],
      title: "NGO Donations",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Our donations investment opportunities cater to the growing demand for efficient and sustainable donations solutions. Partner with Ellington funds to invest in the future of donations.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding3",
      img: donationsThree,
      extraImages: [
        donationsMain,
        donationsSub,
        donationsSubTwo,
        donationsSubThree,
        donationsSubFour,
      ],
      title: "NGO Donations",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Our donations investment opportunities cater to the growing demand for efficient and sustainable donations solutions. Partner with Ellington funds to invest in the future of donations.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding4",
      img: donationsFour,
      extraImages: [
        donationsMain,
        donationsSub,
        donationsSubTwo,
        donationsSubThree,
        donationsSubFour,
      ],
      title: "NGO Donations",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Our donations investment opportunities cater to the growing demand for efficient and sustainable donations solutions. Partner with Ellington funds to invest in the future of donations.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding5",
      img: donationsFive,
      extraImages: [
        donationsMain,
        donationsSub,
        donationsSubTwo,
        donationsSubThree,
        donationsSubFour,
      ],
      title: "NGO Donations",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Our donations investment opportunities cater to the growing demand for efficient and sustainable donations solutions. Partner with Ellington funds to invest in the future of donations.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding6",
      img: donationsSix,
      extraImages: [
        donationsMain,
        donationsSub,
        donationsSubTwo,
        donationsSubThree,
        donationsSubFour,
      ],
      title: "NGO Donations",
      info: { location: "lekki phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Our donations investment opportunities cater to the growing demand for efficient and sustainable donations solutions. Partner with Ellington funds to invest in the future of donations.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
  ],
};
