import {
  one as restaurantOne,
  three as restaurantThree,
  two as restaurantTwo,
  six as restaurantSix,
  five as restaurantFive,
  four as restaurantFour,
} from "../../../assets/images/services/restaurant/card";

// content images

import {
  main as restaurantMain,
  sub as restaurantSub,
  subTwo as restaurantSubTwo,
  subThree as restaurantSubThree,
  subFour as restaurantSubFour,
} from "../../../assets/images/services/restaurant/product";

export const restaurant = {
  title: "Restaurant",
  id: "restaurant",
  desc: "Are you looking to raise capital for your restaurant? Ellington funds offers fundraising solutions for businesses and individuals, connecting you with potential investors who share your vision.",
  products: [
    {
      id: "crowdfunding1",
      img: restaurantOne,
      extraImages: [
        restaurantMain,
        restaurantSub,
        restaurantSubTwo,
        restaurantSubThree,
        restaurantSubFour,
      ],
      title: "Lekki Restaurant",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds supports the restaurant industry by providing financing options for restaurant owners and investors. Whether you're looking to expand your existing restaurant or start a new venture, we're here to help.Ellington funds supports the restaurant industry by providing financing options for restaurant owners and investors. Whether you're looking to expand your existing restaurant or start a new venture, we're here to help.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding2",
      img: restaurantTwo,
      extraImages: [
        restaurantMain,
        restaurantSub,
        restaurantSubTwo,
        restaurantSubThree,
        restaurantSubFour,
      ],
      title: "Lekki Restaurant",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds supports the restaurant industry by providing financing options for restaurant owners and investors. Whether you're looking to expand your existing restaurant or start a new venture, we're here to help.Ellington funds supports the restaurant industry by providing financing options for restaurant owners and investors. Whether you're looking to expand your existing restaurant or start a new venture, we're here to help.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding3",
      img: restaurantThree,
      extraImages: [
        restaurantMain,
        restaurantSub,
        restaurantSubTwo,
        restaurantSubThree,
        restaurantSubFour,
      ],
      title: "Lekki Restaurant",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds supports the restaurant industry by providing financing options for restaurant owners and investors. Whether you're looking to expand your existing restaurant or start a new venture, we're here to help.Ellington funds supports the restaurant industry by providing financing options for restaurant owners and investors. Whether you're looking to expand your existing restaurant or start a new venture, we're here to help.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding4",
      img: restaurantFour,
      extraImages: [
        restaurantMain,
        restaurantSub,
        restaurantSubTwo,
        restaurantSubThree,
        restaurantSubFour,
      ],
      title: "Lekki Restaurant",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds supports the restaurant industry by providing financing options for restaurant owners and investors. Whether you're looking to expand your existing restaurant or start a new venture, we're here to help.Ellington funds supports the restaurant industry by providing financing options for restaurant owners and investors. Whether you're looking to expand your existing restaurant or start a new venture, we're here to help.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding5",
      img: restaurantFive,
      extraImages: [
        restaurantMain,
        restaurantSub,
        restaurantSubTwo,
        restaurantSubThree,
        restaurantSubFour,
      ],
      title: "Lekki Restaurant",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds supports the restaurant industry by providing financing options for restaurant owners and investors. Whether you're looking to expand your existing restaurant or start a new venture, we're here to help.Ellington funds supports the restaurant industry by providing financing options for restaurant owners and investors. Whether you're looking to expand your existing restaurant or start a new venture, we're here to help.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding6",
      img: restaurantSix,
      extraImages: [
        restaurantMain,
        restaurantSub,
        restaurantSubTwo,
        restaurantSubThree,
        restaurantSubFour,
      ],
      title: "Lekki Restaurant",
      info: { location: "lekki phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds supports the restaurant industry by providing financing options for restaurant owners and investors. Whether you're looking to expand your existing restaurant or start a new venture, we're here to help.Ellington funds supports the restaurant industry by providing financing options for restaurant owners and investors. Whether you're looking to expand your existing restaurant or start a new venture, we're here to help.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
  ],
};
