import {
  one as transportationOne,
  three as transportationThree,
  two as transportationTwo,
  six as transportationSix,
  five as transportationFive,
  four as transportationFour,
} from "../../../assets/images/services/transportation/card";

// content images

import { main as transportationMain } from "../../../assets/images/services/transportation/product";

export const transportation = {
  title: "Transportation",
  id: "transportation",
  desc: "Our transportation investment opportunities cater to the growing demand for efficient and sustainable transportation solutions. Partner with Ellington funds to invest in the future of transportation.",
  products: [
    {
      id: "crowdfunding1",
      img: transportationOne,
      extraImages: [transportationMain],
      title: "Rail Investment",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Our transportation investment opportunities cater to the growing demand for efficient and sustainable transportation solutions. Partner with Ellington funds to invest in the future of transportation.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding2",
      img: transportationTwo,
      extraImages: [transportationMain],
      title: "Bus Investment",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Our transportation investment opportunities cater to the growing demand for efficient and sustainable transportation solutions. Partner with Ellington funds to invest in the future of transportation.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding3",
      img: transportationThree,
      extraImages: [transportationMain],
      title: "Bus Investment",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Our transportation investment opportunities cater to the growing demand for efficient and sustainable transportation solutions. Partner with Ellington funds to invest in the future of transportation.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding4",
      img: transportationFour,
      extraImages: [transportationMain],
      title: "Bus Investment",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Our transportation investment opportunities cater to the growing demand for efficient and sustainable transportation solutions. Partner with Ellington funds to invest in the future of transportation.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding5",
      img: transportationFive,
      extraImages: [transportationMain],
      title: "Bus Investment",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Our transportation investment opportunities cater to the growing demand for efficient and sustainable transportation solutions. Partner with Ellington funds to invest in the future of transportation.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding6",
      img: transportationSix,
      extraImages: [transportationMain],
      title: "Bus Investment",
      info: { location: "lekki phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Our transportation investment opportunities cater to the growing demand for efficient and sustainable transportation solutions. Partner with Ellington funds to invest in the future of transportation.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
  ],
};
