// Card images

import {
  one as crowdOne,
  three as crowdThree,
  two as crowdTwo,
  six as crowdSix,
  five as crowdFive,
  four as crowdFour,
} from "../../../assets/images/services/crowdfunding/card";

import {
  // main as crowdMain,
  sub as crowdSub,
  subTwo as crowdSubTwo,
  subThree as crowdSubThree,
  subFour as crowdSubFour,
} from "../../../assets/images/services/crowdfunding/product";

export const crowdFunding = {
  title: "Crowdfunding For Real Estate",
  id: "crowdfunding",
  desc: "Ellington funds offers tailored property investment opportunities, whether you're looking to invest in residential, commercial, or industrial properties. Our team of experts will guide you through the process, ensuring you make informed decisions that align with your investment objectives.",
  products: [
    {
      id: "crowdfunding1",
      img: crowdOne,
      extraImages: [null, crowdSub, crowdSubTwo, crowdSubThree, crowdSubFour],
      title: "Lekki Phase 1 Lagos Island",
      info: { location: "Lekki Phase 1", bedroom: 2 },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds offers tailored property investment opportunities, whether you're looking to invest in residential, commercial, or industrial properties. Our team of experts will guide you through the process, ensuring you make informed decisions that align with your investment objectives.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding2",
      img: crowdTwo,
      extraImages: [null, crowdSub, crowdSubTwo, crowdSubThree, crowdSubFour],
      title: "Lekki Phase 1 Lagos Island",
      info: { location: "Lekki Phase 1", bedroom: 2 },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds offers tailored property investment opportunities, whether you're looking to invest in residential, commercial, or industrial properties. Our team of experts will guide you through the process, ensuring you make informed decisions that align with your investment objectives.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding3",
      img: crowdThree,
      extraImages: [null, crowdSub, crowdSubTwo, crowdSubThree, crowdSubFour],
      title: "Lekki Phase 1 Lagos Island",
      info: { location: "Lekki Phase 1", bedroom: 2 },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds offers tailored property investment opportunities, whether you're looking to invest in residential, commercial, or industrial properties. Our team of experts will guide you through the process, ensuring you make informed decisions that align with your investment objectives.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding4",
      img: crowdFour,
      extraImages: [null, crowdSub, crowdSubTwo, crowdSubThree, crowdSubFour],
      title: "Lekki Phase 1 Lagos Island",
      info: { location: "Lekki Phase 1", bedroom: 2 },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds offers tailored property investment opportunities, whether you're looking to invest in residential, commercial, or industrial properties. Our team of experts will guide you through the process, ensuring you make informed decisions that align with your investment objectives.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding5",
      img: crowdFive,
      extraImages: [null, crowdSub, crowdSubTwo, crowdSubThree, crowdSubFour],
      title: "Lekki Phase 1 Lagos Island",
      info: { location: "Lekki Phase 1", bedroom: 2 },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds offers tailored property investment opportunities, whether you're looking to invest in residential, commercial, or industrial properties. Our team of experts will guide you through the process, ensuring you make informed decisions that align with your investment objectives.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding6",
      img: crowdSix,
      extraImages: [null, crowdSub, crowdSubTwo, crowdSubThree, crowdSubFour],
      title: "Lekki Phase 1 Lagos Island",
      info: { location: "Lekki Phase 1", bedroom: 2 },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds offers tailored property investment opportunities, whether you're looking to invest in residential, commercial, or industrial properties. Our team of experts will guide you through the process, ensuring you make informed decisions that align with your investment objectives.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
  ],
};
