import {
  one as projectOne,
  three as projectThree,
  two as projectTwo,
  six as projectSix,
  five as projectFive,
  four as projectFour,
} from "../../../assets/images/services/project/card";

// content images

import {
  main as projectMain,
  sub as projectSub,
  subTwo as projectSubTwo,
  subThree as projectSubThree,
  subFour as projectSubFour,
} from "../../../assets/images/services/project/product";

export const project = {
  title: "Project Funding",
  id: "project-funding",
  desc: "Are you looking to raise capital for your project? Ellington funds offers fundraising solutions for businesses and individuals, connecting you with potential investors who share your vision.",
  products: [
    {
      id: "crowdfunding1",
      img: projectOne,
      extraImages: [
        projectMain,
        projectSub,
        projectSubTwo,
        projectSubThree,
        projectSubFour,
      ],
      title: "Project 1",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds offers tailored property investment opportunities, whether you're looking to invest in residential, commercial, or industrial properties. Our team of experts will guide you through the process, ensuring you make informed decisions that align with your investment objectives.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding2",
      img: projectTwo,
      extraImages: [
        projectMain,
        projectSub,
        projectSubTwo,
        projectSubThree,
        projectSubFour,
      ],
      title: "Project 1",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds offers tailored property investment opportunities, whether you're looking to invest in residential, commercial, or industrial properties. Our team of experts will guide you through the process, ensuring you make informed decisions that align with your investment objectives.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding3",
      img: projectThree,
      extraImages: [
        projectMain,
        projectSub,
        projectSubTwo,
        projectSubThree,
        projectSubFour,
      ],
      title: "Project 1",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds offers tailored property investment opportunities, whether you're looking to invest in residential, commercial, or industrial properties. Our team of experts will guide you through the process, ensuring you make informed decisions that align with your investment objectives.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding4",
      img: projectFour,
      extraImages: [
        projectMain,
        projectSub,
        projectSubTwo,
        projectSubThree,
        projectSubFour,
      ],
      title: "Project 1",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds offers tailored property investment opportunities, whether you're looking to invest in residential, commercial, or industrial properties. Our team of experts will guide you through the process, ensuring you make informed decisions that align with your investment objectives.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding5",
      img: projectFive,
      extraImages: [
        projectMain,
        projectSub,
        projectSubTwo,
        projectSubThree,
        projectSubFour,
      ],
      title: "Project 1",
      info: { location: "Lekki Phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds offers tailored property investment opportunities, whether you're looking to invest in residential, commercial, or industrial properties. Our team of experts will guide you through the process, ensuring you make informed decisions that align with your investment objectives.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
    {
      id: "crowdfunding6",
      img: projectSix,
      extraImages: [
        projectMain,
        projectSub,
        projectSubTwo,
        projectSubThree,
        projectSubFour,
      ],
      title: "Project 1",
      info: { location: "lekki phase 1" },
      financials: {
        investors: 134,
        returns: 11.1,
        valuation: 900000,
        fee: 11.1,
        propertyPrice: 900000,
        cost: 900000,
      },
      desc: "Ellington funds offers tailored property investment opportunities, whether you're looking to invest in residential, commercial, or industrial properties. Our team of experts will guide you through the process, ensuring you make informed decisions that align with your investment objectives.",
      overview: `An chance to purchase a studio flat in Lekki phase 1 Towers is being provided by Ellington funds. Lekki Phase 1 is a carefully designed area in Lagos, Nigeria, renowned for its artificial parks and lakes. With a lot of high-rise apartment buildings that provide flats and offices with views over the lakes, it's a well-liked residential and business center. Lekki Phase 1 is a sought-after neighborhood in Lagos with a variety of food options and recreational amenities.Situated in Lekki Phase 1, LK1Towers is a residential complex made up of three buildings. The 700 units at LK 1Tower 3's 36 stories range from studios to 5-bed penthouses.`,
      document: [
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
        { name: "property1- real estate" },
      ],
    },
  ],
};
